server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CitadelLibrary
    username: realestate_user
    password: cosmos12345
    driver-class-name: org.postgresql.Driver


  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

citadel_library:
  app:
    jwtSecret: Citadel@12
    jwtExpirationMs: 86400000

logging:
  file:
    name: logs/CitadelLibrary.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"

  level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO
    '[com.Citadellibrary]': DEBUG

springdoc:
  api-docs:
    path=/api-docs: